### ISSUE TITLE
Failed to activate the mr-bookmark package

### ISSUE THREAD

**Issue by IoStoQui** [HerrSteen/mr-bookmark#7]
**Atom**: 1.36.0 ia32
**Electron**: 2.0.18
**OS**: Microsoft Windows 7 Enterprise 
**Thrown From**: [mr-bookmark](https://github.com/HerrSteen/mr-bookmark) package 0.8.0

### Stack Trace

Failed to activate the mr-bookmark package

```
At Cannot read property 'onDidChangeStatus' of null

TypeError: Cannot read property 'onDidChangeStatus' of null
    at MrGit.addChangeListener (/packages/mr-bookmark/lib/mr-git.js:57:15)
    at /packages/mr-bookmark/lib/mr-git.js:9:10)
    at Object.activate (/packages/mr-bookmark/lib/mr-bookmark.js:19:18)
    at Package.activateNow (~/AppData/Local/atom/app-1.36.0/resources/app/static/<embedded>:11:3175180)
    at measure (~/AppData/Local/atom/app-1.36.0/resources/app/static/<embedded>:11:3174592)
    at Package.measure (~/AppData/Local/atom/app-1.36.0/resources/app/static/<embedded>:11:3172223)
    at activationPromise.activationPromise.Promise (~/AppData/Local/atom/app-1.36.0/resources/app/static/<embedded>:11:3174452)
    at new Promise (<anonymous>)
    at Package.activate (~/AppData/Local/atom/app-1.36.0/resources/app/static/<embedded>:11:3174395)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.36.0/resources/app/static/<embedded>:11:382747)
    at ~/AppData/Local/atom/app-1.36.0/resources/app/static/<embedded>:11:899012
    at r (~/AppData/Local/atom/app-1.36.0/resources/app/static/<embedded>:11:893618)
    at o (~/AppData/Local/atom/app-1.36.0/resources/app/static/<embedded>:14:1032937)
    at t.bufferStream (~/AppData/Local/atom/app-1.36.0/resources/app/static/<embedded>:14:1033091)
    at Socket.e.on (~/AppData/Local/atom/app-1.36.0/resources/app/static/<embedded>:14:1031693)
    at emitOne (events.js:121:20)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)
```

### Commands

```
  7x -9:10.4.0 core:backspace (input.hidden-input)
  3x -4:21.4.0 emmet:select-previous-item (atom-pane.pane)
     -4:02.4.0 emmet:select-next-item (atom-pane.pane)
     -4:01.9.0 emmet:select-previous-item (atom-pane.pane)
     -4:01.7.0 emmet:select-next-item (atom-pane.pane)
     -4:01.5.0 window:decrease-font-size (atom-pane.pane)
     -3:54.5.0 settings-view:uninstall-themes (atom-pane.pane)
```

### Non-Core Packages

```
drag-relative-path 1.1.3 
emmet 2.4.3 
file-bookmark 1.0.4 (also without)
file-icons 2.1.31 
local-history 4.3.1 
minimap 4.29.9 
mr-bookmark 0.8.0 
open-in-browsers 0.0.30 
open-recent 5.0.0 
todo-show 2.3.2 
```

**Comment by HerrSteen** [comment]
Hi, I will take a look at this.
